# Generated by Django 4.2.14 on 2024-07-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='price_per_PSC',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
